/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as QuotationRouteImport } from './routes/quotation'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as PortalOrdersRouteImport } from './routes/portal.orders'
import { Route as PortalLeadsRouteImport } from './routes/portal.leads'
import { Route as PortalKpisRouteImport } from './routes/portal.kpis'
import { Route as PortalInquiriesRouteImport } from './routes/portal.inquiries'
import { Route as PortalDocumentsRouteImport } from './routes/portal.documents'
import { Route as PortalCommissionsRouteImport } from './routes/portal.commissions'
import { Route as PortalCatalogRouteImport } from './routes/portal.catalog'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminSuppliersRouteImport } from './routes/admin.suppliers'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminQuotationsRouteImport } from './routes/admin.quotations'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AccountQuotationsRouteImport } from './routes/account.quotations'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account.orders.$orderId'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationRoute = QuotationRouteImport.update({
  id: '/quotation',
  path: '/quotation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRoute,
} as any)
const PortalOrdersRoute = PortalOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLeadsRoute = PortalLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => PortalRoute,
} as any)
const PortalKpisRoute = PortalKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInquiriesRoute = PortalInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCommissionsRoute = PortalCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCatalogRoute = PortalCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => PortalRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotationsRoute = AdminQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AccountQuotationsRoute = AccountQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AccountOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/quotation': typeof QuotationRoute
  '/suppliers': typeof SuppliersRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/account/quotations': typeof AccountQuotationsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/quotations': typeof AdminQuotationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/portal/catalog': typeof PortalCatalogRoute
  '/portal/commissions': typeof PortalCommissionsRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/inquiries': typeof PortalInquiriesRoute
  '/portal/kpis': typeof PortalKpisRoute
  '/portal/leads': typeof PortalLeadsRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/partners': typeof PartnersRoute
  '/products': typeof ProductsRouteWithChildren
  '/quotation': typeof QuotationRoute
  '/suppliers': typeof SuppliersRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/account/quotations': typeof AccountQuotationsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/quotations': typeof AdminQuotationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/portal/catalog': typeof PortalCatalogRoute
  '/portal/commissions': typeof PortalCommissionsRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/inquiries': typeof PortalInquiriesRoute
  '/portal/kpis': typeof PortalKpisRoute
  '/portal/leads': typeof PortalLeadsRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/quotation': typeof QuotationRoute
  '/suppliers': typeof SuppliersRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/account/quotations': typeof AccountQuotationsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/quotations': typeof AdminQuotationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/portal/catalog': typeof PortalCatalogRoute
  '/portal/commissions': typeof PortalCommissionsRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/inquiries': typeof PortalInquiriesRoute
  '/portal/kpis': typeof PortalKpisRoute
  '/portal/leads': typeof PortalLeadsRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/agents'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/industries'
    | '/partners'
    | '/portal'
    | '/products'
    | '/quotation'
    | '/suppliers'
    | '/account/orders'
    | '/account/profile'
    | '/account/quotations'
    | '/account/wishlist'
    | '/admin/agents'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/quotations'
    | '/admin/reports'
    | '/admin/suppliers'
    | '/auth/login'
    | '/auth/register'
    | '/portal/catalog'
    | '/portal/commissions'
    | '/portal/documents'
    | '/portal/inquiries'
    | '/portal/kpis'
    | '/portal/leads'
    | '/portal/orders'
    | '/products/$productId'
    | '/account/'
    | '/admin/'
    | '/portal/'
    | '/account/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/industries'
    | '/partners'
    | '/products'
    | '/quotation'
    | '/suppliers'
    | '/account/orders'
    | '/account/profile'
    | '/account/quotations'
    | '/account/wishlist'
    | '/admin/agents'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/quotations'
    | '/admin/reports'
    | '/admin/suppliers'
    | '/auth/login'
    | '/auth/register'
    | '/portal/catalog'
    | '/portal/commissions'
    | '/portal/documents'
    | '/portal/inquiries'
    | '/portal/kpis'
    | '/portal/leads'
    | '/portal/orders'
    | '/products/$productId'
    | '/account'
    | '/admin'
    | '/portal'
    | '/account/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/agents'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/industries'
    | '/partners'
    | '/portal'
    | '/products'
    | '/quotation'
    | '/suppliers'
    | '/account/orders'
    | '/account/profile'
    | '/account/quotations'
    | '/account/wishlist'
    | '/admin/agents'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/quotations'
    | '/admin/reports'
    | '/admin/suppliers'
    | '/auth/login'
    | '/auth/register'
    | '/portal/catalog'
    | '/portal/commissions'
    | '/portal/documents'
    | '/portal/inquiries'
    | '/portal/kpis'
    | '/portal/leads'
    | '/portal/orders'
    | '/products/$productId'
    | '/account/'
    | '/admin/'
    | '/portal/'
    | '/account/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  PartnersRoute: typeof PartnersRoute
  PortalRoute: typeof PortalRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  QuotationRoute: typeof QuotationRoute
  SuppliersRoute: typeof SuppliersRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotation': {
      id: '/quotation'
      path: '/quotation'
      fullPath: '/quotation'
      preLoaderRoute: typeof QuotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/portal/orders': {
      id: '/portal/orders'
      path: '/orders'
      fullPath: '/portal/orders'
      preLoaderRoute: typeof PortalOrdersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/leads': {
      id: '/portal/leads'
      path: '/leads'
      fullPath: '/portal/leads'
      preLoaderRoute: typeof PortalLeadsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/kpis': {
      id: '/portal/kpis'
      path: '/kpis'
      fullPath: '/portal/kpis'
      preLoaderRoute: typeof PortalKpisRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/inquiries': {
      id: '/portal/inquiries'
      path: '/inquiries'
      fullPath: '/portal/inquiries'
      preLoaderRoute: typeof PortalInquiriesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/commissions': {
      id: '/portal/commissions'
      path: '/commissions'
      fullPath: '/portal/commissions'
      preLoaderRoute: typeof PortalCommissionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/catalog': {
      id: '/portal/catalog'
      path: '/catalog'
      fullPath: '/portal/catalog'
      preLoaderRoute: typeof PortalCatalogRouteImport
      parentRoute: typeof PortalRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotations': {
      id: '/admin/quotations'
      path: '/quotations'
      fullPath: '/admin/quotations'
      preLoaderRoute: typeof AdminQuotationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/quotations': {
      id: '/account/quotations'
      path: '/quotations'
      fullPath: '/account/quotations'
      preLoaderRoute: typeof AccountQuotationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
  }
}

interface AccountOrdersRouteChildren {
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface AccountRouteChildren {
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountProfileRoute: typeof AccountProfileRoute
  AccountQuotationsRoute: typeof AccountQuotationsRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountProfileRoute: AccountProfileRoute,
  AccountQuotationsRoute: AccountQuotationsRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminQuotationsRoute: typeof AdminQuotationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentsRoute: AdminAgentsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminQuotationsRoute: AdminQuotationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalRouteChildren {
  PortalCatalogRoute: typeof PortalCatalogRoute
  PortalCommissionsRoute: typeof PortalCommissionsRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalInquiriesRoute: typeof PortalInquiriesRoute
  PortalKpisRoute: typeof PortalKpisRoute
  PortalLeadsRoute: typeof PortalLeadsRoute
  PortalOrdersRoute: typeof PortalOrdersRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalCatalogRoute: PortalCatalogRoute,
  PortalCommissionsRoute: PortalCommissionsRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalInquiriesRoute: PortalInquiriesRoute,
  PortalKpisRoute: PortalKpisRoute,
  PortalLeadsRoute: PortalLeadsRoute,
  PortalOrdersRoute: PortalOrdersRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface ProductsRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AgentsRoute: AgentsRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  PartnersRoute: PartnersRoute,
  PortalRoute: PortalRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  QuotationRoute: QuotationRoute,
  SuppliersRoute: SuppliersRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
